### ISSUE TITLE
Inform about 24 hour timeout

### ISSUE THREAD

**Issue by Griatch** [gtaylor/evennia-game-index#2]
If a game changes their name or makes some other change to their setup identifying them as a different game, their old entry will remain until it's auto-cleaned. To avoid questions/bug reports about this, mentioning the 24 hour timeout on the front page somewhere is probably a good idea. Overall, letting people know that a game will be auto-removed if inactive for 24 hours is a good way to hint to users that the list is kept up-to-date.

**Comment by gtaylor** [comment]
I've knocked this down to two hours, since 24 was entirely too long. The listings aren't deleted either way, so URLs out in the wild will be preserved. I could go down to one hour if we reduce the checkin interval from 15 minutes to 30.

I'm going to try to pare down some of the information on the front page, and am hesitant to add too much more. I've been thinking about creating a FAQ page and moving some of the stuff on the index over.
